targets:
  $default:
    builders:
      graphql_codegen:
        options:
          assetPath: lib/schema/**.{graphql,graphqls}
          generatedFileHeader: "// ignore_for_file: type=lint\n"
          clients:
            - graphql
            - graphql_flutter